# Generated by Django 3.1.7 on 2021-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_auto_20210413_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=None),
        ),
    ]
